### ISSUE TITLE
Cannot verif account MLBB

### ISSUE THREAD

**Issue by muhammad-dicky** [entry-point-community/mabar-fun#15] opened 2023-11-13 14:27 UTC
![image](https://github.com/entry-point-community/mabar-fun/assets/58357765/1ae75be0-808b-4322-beff-6b4aa5dbbef3)

Cannot verif account MLBB

**Comment by theodevoid** [comment] 2023-11-13 14:46
Duplicate of #14 . Closing this...

**Closed as completed by theodevoid** 2023-11-13 14:46 UTC
